name: CI

on:
  push:
    branches: 
      - main
      
jobs:
  db-deploy:
    name: db-deploy
    runs-on: self-hosted

    steps:
#     - uses: azure/login@v1
#       with:
#         creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: debug
        run: |
          pwd
          ls -ltra
                
#     - name: RunLiquibase
#       run: | 
#           liquibase \
#           --changeLogFile=db_files/changelogs/changelog2.sql \
#           --url="jdbc:sqlserver://$DB_SERVER_NAME.database.windows.net:1433;database=$DB_DB_NAME" \
#           --username="$DB_USER_NAME" \
#           --password="$DB_PASSWORD" \
#           status
          
      - name: Liquibase Github Action
        # You may pin to the exact commit or the version.
        # uses: liquibase/liquibase-github-action@480ea2b6ba0026b980ae81f459286ca80f2bf75f
        uses: liquibase/liquibase-github-action@v2
        with:
          # Operation to run
          operation: update
          # Path to Change Log directory
          classpath: 'db_files/changelogs'
          # Name of Change Log File
          changeLogFile: 'changelog2.sql'
          # Database Username
          username: ${{ secrets.DB_USER_NAME }}
          # Database Password
          password: ${{ secrets.DB_PASSWORD }}
          # Database URL
          url: ${{ secrets.DB_URL }}
