name: CI

on:
  push:
    branches: 
      - fix-yml-file
      
jobs:
  db-deploy:
    name: db-deploy
    runs-on: ubuntu-latest

    steps:        
      - name: Checkout
        uses: actions/checkout@v2
                        
#     - name: RunLiquibase
#       run: | 
#           liquibase \
#           --changeLogFile=db_files/changelogs/changelog2.sql \
#           --url="jdbc:sqlserver://$DB_SERVER_NAME.database.windows.net:1433;database=$DB_DB_NAME" \
#           --username="$DB_USER_NAME" \
#           --password="$DB_PASSWORD" \
#           status

      - name: Azure Login
        uses: Azure/login@v1
        with:
          # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Liquibase Github Action
        # You may pin to the exact commit or the version.
        # uses: liquibase/liquibase-github-action@480ea2b6ba0026b980ae81f459286ca80f2bf75f
        uses: liquibase/liquibase-github-action@v2
        with:
          # Operation to run
          operation: update
          # Path to Change Log directory
          classpath: 'db_files'
          # Name of Change Log File
          changeLogFile: 'changelogs/changelog3.json'
          # Database Username
          username: ${{ secrets.DB_USER_NAME }}
          # Database Password
          password: ${{ secrets.DB_PASSWORD }}
          # Database URL
          url: ${{ secrets.DB_URL }}
